import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const projectDirectory = path.resolve(scriptDirectory, '..');
const inputDirectory = path.join(projectDirectory, 'input');
const outputFile = path.join(projectDirectory, 'src', 'generated-poems.ts');

const titlePattern = /《([^《》\r\n]{1,80})》\s*([\s\S]*?)(?=《[^《》\r\n]{1,80}》|$)/g;

const findJsonFiles = async (directory) => {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = await Promise.all(entries.map(async (entry) => {
    const entryPath = path.join(directory, entry.name);
    if (entry.isDirectory()) return findJsonFiles(entryPath);
    return entry.isFile() && entry.name.endsWith('.json') ? [entryPath] : [];
  }));

  return files.flat().sort((left, right) => left.localeCompare(right, 'zh-Hans-CN'));
};

const cleanLines = (body) => body
  .replace(/^:::writing\{[^}]*}\s*$/gm, '')
  .replace(/^:::\s*$/gm, '')
  .replace(/\r/g, '')
  .split('\n')
  .map((line) => line.replace(/\s+$/g, '').trim())
  .filter(Boolean);

const extractPoems = (conversation, source) => {
  const messages = Object.values(conversation.mapping ?? {})
    .map((node) => node?.message)
    .filter((message) => message?.author?.role === 'assistant')
    .sort((left, right) => (left.create_time ?? 0) - (right.create_time ?? 0));

  const poems = [];
  for (const message of messages) {
    const content = (message.content?.parts ?? [])
      .filter((part) => typeof part === 'string')
      .join('\n');

    for (const match of content.matchAll(titlePattern)) {
      const title = match[1].trim();
      const lines = cleanLines(match[2]);

      // A title alone is not a poem. This also avoids importing prose that
      // happens to quote a book or poem title in a conversation response.
      if (title && lines.length >= 2) {
        poems.push({ title, lines, source });
      }
    }
  }

  return poems;
};

const createModule = (poems) => `// This file is generated by scripts/import-poems.mjs. Do not edit manually.\nimport type { Poem } from './types';\n\nexport const POEM_COUNT = ${poems.length};\n\nexport const poems: Poem[] = ${JSON.stringify(poems, null, 2)};\n`;

const files = await findJsonFiles(inputDirectory);
const extracted = [];

for (const file of files) {
  const conversation = JSON.parse(await readFile(file, 'utf8'));
  const source = String(conversation.title ?? path.basename(file, '.json')).trim();
  extracted.push(...extractPoems(conversation, source));
}

const seen = new Set();
const poems = [];
for (const poem of extracted) {
  const key = `${poem.title}\u0000${poem.lines.join('\n')}`;
  if (seen.has(key)) continue;
  seen.add(key);
  poems.push({
    id: poems.length + 1,
    title: poem.title,
    author: '对话归档',
    lines: poem.lines,
    tags: [poem.source],
  });
}

await mkdir(path.dirname(outputFile), { recursive: true });
await writeFile(outputFile, createModule(poems), 'utf8');

console.log(`已从 ${files.length} 个 JSON 文件中提取 ${extracted.length} 首诗。`);
console.log(`去重后已导入 ${poems.length} 首诗：${path.relative(projectDirectory, outputFile)}`);
